name: Deploy Next.js to Server

on:
  push:
    branches:
      - main  # Ändern, falls du einen anderen Branch deployen willst

jobs:
  deploy:
    runs-on: debian-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Anpassen an deine Node-Version

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: ".,!node_modules"
          target: "/var/www/ollipolli.de/public_html/nextjs-app"

      - name: Restart Application
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /var/www/ollipolli.de/public_html/nextjs-app
            npm install --production
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
